### ISSUE TITLE
Plex using the wrong actor thumb in different shows

### ISSUE THREAD

**Issue by andres-asm** [gboudreau/XBMCnfoTVImporter.bundle#118]
It seems this is a problem with the importer according to the plex forums
For instance, if I rescan breaking bad, this is Bob Odenkirk on all shows he appears:

![imagen](https://user-images.githubusercontent.com/1721040/109661418-f6dc9100-7b37-11eb-9ded-a68a425f2a4c.png)

![imagen](https://user-images.githubusercontent.com/1721040/109661431-fa701800-7b37-11eb-90de-964dbe90f79f.png)

But if I go to Better Call Saul it’s wrong, should be this one:

![imagen](https://user-images.githubusercontent.com/1721040/109661462-00fe8f80-7b38-11eb-87d0-f5a4b21ce39e.png)

![imagen](https://user-images.githubusercontent.com/1721040/109661480-04921680-7b38-11eb-9725-d3b0325ebbfe.png)

And on Fargo too…
If I were to update thumbs on Fargo, then the fargo thumb of Bob Odenkirk would shouw up on all shows instead.

TheTVDB has nice thumbs for each show, so it would be ideal if the thumb was not tied to the actor name but the actor name/show name tuple.

**Comment by UkklyDukkling** [comment]
@fr500 What you have described is Plex's intended functionality. All instances of an actor are linked together in the Plex database as one entry, giving the benefit of clicking on an actor thumbnail in one show in order to pull up a list of all shows that actor is in. The downside to this is that Plex then also serves up a single image for all thumbnails of that actor (the image is from your most recently added/metadata refreshed show, as you noted).

This plugin cannot change Plex's functionality in this regard, and unfortunately it seems that Plex's dev team has no plans to support different actor images per show.
